services:
  - type: web
    name: fastapi-items-api
    env: python
    buildCommand: |
      if [ ! -f requirements.txt ]; then
        echo "!!! ERREUR: requirements.txt introuvable !!!"
        ls -la
        exit 1
      fi
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
